services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: board-todo-app
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - board-todo-app-net

networks:
  board-todo-app-net:
    driver: bridge